### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by OlegArnautov** [AMATEURZ1337/load-lib-injector#1]
It's not working, me crashed.

**Comment by cccp3** [comment]
it's problem with dll
i tried different dll and work ok

**Comment by OlegArnautov** [comment]
> it's problem with dll
> at first i had same problem when injecting in beta with secure_launch 1
> i tried different dll and work ok

My cheat worked, but not now. Beta worked before new update.

**Comment by VJdL26** [comment]
Hi bro, where should I start learning C++? Specifically about hacking related. :D

**Comment by RetiredQQ** [comment]
@VJdL26 I suggest you go to guidedhacking.com

**Comment by v3ctra** [comment]
There is nothing to fix, csgo crashed due to your dll.
Issue Closed.
