### ISSUE TITLE
faceit support

### ISSUE THREAD

**Issue by Mercurial** [AMATEURZ1337/load-lib-injector#13]
hi, is it possible that this can work on faceit? 

Thanks!

**Comment by Yatagarasu-dev** [comment]
> hi, is it possible that this can work on faceit?
> 
> Thanks!

**NOT!** To bypass the faceit anti-cheat, you need to write a kernel injector or cheat

**Comment by barry-mcockiner** [comment]
you are literally braindead

**Comment by v3ctra** [comment]
This is impossible in its current state.
