### ISSUE TITLE
A lot of errors

### ISSUE THREAD

**Issue by kruzgi** [AMATEURZ1337/load-lib-injector#2]
I get of errors when i try to compile (7) i use 2019 and i have most of the c++ components 
i have these 3 things installed (i checked all things in there)
![aezakmi](https://user-images.githubusercontent.com/57067715/87043279-1152aa80-c1f5-11ea-875b-30c032c627fa.png)
there are errors that im getting
![errors](https://user-images.githubusercontent.com/57067715/87043616-98078780-c1f5-11ea-8286-bc070c87f920.png)

**Comment by AMATEURZ1337** [comment]
Use Multi-Byte Character Set and add _CRT_SECURE_NO_WARNINGS in preprocesor options.

**Comment by VuBrian22** [comment]
Compile it in the x86 architecture and not x64.

**Comment by MasterChief220** [comment]
If it still gives error C4996 then :
open the Property Pages dialog for your project. For information on how to use the Property Pages dialog, see Property Pages.

Select the Configuration Properties > C/C++ > Advanced property page.

Edit the Disable Specific Warnings property to add 4996. Choose OK to apply your changes.
