### ISSUE TITLE
Junk bytes

### ISSUE THREAD

**Issue by kuk1u1brak1uku1bra2506** [AMATEURZ1337/load-lib-injector#3]
Hello. Is that possible to add junk bytes into the injector source code?
I used rando injector before csgo update. There was a lot of bytes, it was always undetected because just me used that.
Any ideas? 
Have a nice day! 😊

**Comment by kvetinkavole** [comment]
Just use junkcode generator
https://junkcode.gehaxelt.in/
https://www.unknowncheats.me/forum/c-and-c-/231044-junk-code-generator.html

**Comment by AMATEURZ1337** [comment]
Hey!

It's 100% possible. Check how bytes in rando-injector works, and paste them if want, you can also use generators, that @kvetinkavole already sent.

Have a nice day :)

**Comment by unnamed01X** [comment]
> Hey!
> 
> It's 100% possible. Check how bytes in rando-injector works, and paste them if want, you can also use generators, that @kvetinkavole already sent.
> 
> Have a nice day :)

what do you mean? could you help me with that please?

**Comment by v3ctra** [comment]
Closed due to user's brain issue.
