### ISSUE TITLE
it works，use the release version

### ISSUE THREAD

**Issue by Guanzhe** [AMATEURZ1337/load-lib-injector#6]

**Comment by VuBrian22** [comment]
Or compile the injector using the x86 architecture and not the x64 architecture. A lot of people just run into errors when they are compiling the source. This is in relation to #2.

**Comment by v3ctra** [comment]
Hi!

Release version is the same as source.
If you mean errors in source, make sure you building with following configuration (visual studio on screen):
![image](https://user-images.githubusercontent.com/40214342/87424513-5c493500-c5dc-11ea-93e7-42052f6c0494.png)

Have a nice day! :)
